### ISSUE TITLE
Pull Requests

### ISSUE THREAD

**Issue by hangtime79** [IBMPredictiveAnalytics/The_Weather_Company_Airport_Observations#2]
@Wenpei can you take a look at the changes I made in the Pull Request and if good promote to the master? Thanks!

**Comment by Wenpei** [comment]
@hangtime79 thank you very much.
I will take a try when I back to office.

**Comment by Wenpei** [comment]
@hangtime79 
It's realy great for you PR, and make this extension more robust and user friendly.

One thing is.
Can you add long time(more than 31 days) process, since old extenison support this.

Below code split start end date, and process it month by month. 
```
  for(day in format(seq(sStartDate,sEndDate,30),"%Y%m%d")){
    dayNumber <- as.Date(day,"%Y%m%d")
    sMonthStartDate <- day#format(day,"%Y%m%d")
    if(dayNumber + 30 > sEndDate )
      sMonthEndDate <- format(sEndDate,"%Y%m%d")
    else
      sMonthEndDate <- format(dayNumber + 30,"%Y%m%d")
    sDateRange = paste("&startDate=", 
                       sMonthStartDate, "&endDate=", 
                       sMonthEndDate, sep="")
    sRequestURL <- generateUrl(sLocationUrl,sDateRange)
    print(sRequestURL)
    resultData <- rbind(resultData,retriveDataFromTWC_OneMonth(sRequestURL))
    print(nrow(resultData))
  }
```

another thing is about 
```
packages <- function(x){
  x <- as.character(match.call()[[2]])
  if (!require(x,character.only=TRUE)){
    install.packages(pkgs=x,repos="http://cran.r-project.org")
    require(x,character.only=TRUE)
  }
}
```
this function try to auto install required package. but you didn't use it in extension.
But I am OK if you don't want it, because it may cause a protention issues, when some package updated(install.packages will install latest package). 

Thank you very much.
Yu Wenpei.

**Comment by Wenpei** [comment]
I will close this issues and we can trace it in pr #1
